### PR TITLE
Fixes for open qrcode as none

### PR DESCRIPTION
**Pull request by BruceZhang1993**

### CODE REVIEW

**Comment by OriginCode** [comment]
Being merged (Scheduled on this weekend)!
Thank you very much!

**Comment by OriginCode** [comment]
@BruceZhang1993 某兔兔给了个PR（

**Comment by BruceZhang1993** [comment]
@OriginCode Dr. OC prpr.

**Comment by OriginCode** [comment]
@BruceZhang1993 ...

**Pull request merged**
